# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_designs/combo_box.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ComboBoxTutorial(object):
    def setupUi(self, ComboBoxTutorial):
        ComboBoxTutorial.setObjectName("ComboBoxTutorial")
        ComboBoxTutorial.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ComboBoxTutorial)
        self.centralwidget.setObjectName("centralwidget")

        # combo box 1
        self.x = QtWidgets.QComboBox(self.centralwidget)
        self.x.setGeometry(QtCore.QRect(100, 220, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.x.setFont(font)
        self.x.setEditable(False)
        self.x.setObjectName("x")
        self.x.addItem("")
        self.x.addItem("")

        # a label for the x combo box
        self.x_label = QtWidgets.QLabel(self.centralwidget)
        self.x_label.setGeometry(QtCore.QRect(90, 140, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.x_label.setFont(font)
        self.x_label.setObjectName("x_label")

        # combo box 2
        self.y = QtWidgets.QComboBox(self.centralwidget)
        self.y.setGeometry(QtCore.QRect(480, 220, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.y.setFont(font)
        self.y.setObjectName("y")
        self.y.addItem("")
        self.y.addItem("")

        # a label for the y combo box
        self.y_label = QtWidgets.QLabel(self.centralwidget)
        self.y_label.setGeometry(QtCore.QRect(470, 140, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.y_label.setFont(font)
        self.y_label.setObjectName("y_label")

        # answer label
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(220, 350, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setObjectName("result")

        # the submit button
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(280, 430, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.submit.setFont(font)
        self.submit.setObjectName("submit")

        # title label
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(210, 10, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")

        # menubar and statusbar we don't need
        ComboBoxTutorial.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ComboBoxTutorial)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        ComboBoxTutorial.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(ComboBoxTutorial)
        self.statusbar.setObjectName("statusbar")
        ComboBoxTutorial.setStatusBar(self.statusbar)

        # call the pressed function when the submit button is clicked
        self.submit.clicked.connect(self.pressed)

        self.retranslateUi(ComboBoxTutorial)
        QtCore.QMetaObject.connectSlotsByName(ComboBoxTutorial)

    def retranslateUi(self, ComboBoxTutorial):
        _translate = QtCore.QCoreApplication.translate
        ComboBoxTutorial.setWindowTitle(_translate("ComboBoxTutorial", "MainWindow"))
        self.x.setItemText(0, _translate("ComboBoxTutorial", "0"))
        self.x.setItemText(1, _translate("ComboBoxTutorial", "1"))
        self.y.setItemText(0, _translate("ComboBoxTutorial", "0"))
        self.y.setItemText(1, _translate("ComboBoxTutorial", "1"))
        self.result.setText(_translate("ComboBoxTutorial", "X XOR Y ="))
        self.x_label.setText(_translate("ComboBoxTutorial", "Choose X value"))
        self.y_label.setText(_translate("ComboBoxTutorial", "Choose Y value"))
        self.submit.setText(_translate("ComboBoxTutorial", "submit"))
        self.title_label.setText(_translate("ComboBoxTutorial", "Calculate the XOR function"))

    def pressed(self):
        """gets which value the user presses and computes the xor function."""

        x = int(self.x.currentText())
        y = int(self.y.currentText())

        # computes the xor function
        xor = (x and not y) or (not x and y)

        self.result.setText(f"X XOR = {str(xor)}")
        self.result.adjustSize()


if __name__ == "__main__":
    import sys, os

    basedir = os.path.dirname(__file__)
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon(os.path.join(basedir, "images/direction.png")))
    ComboBoxTutorial = QtWidgets.QMainWindow()
    ui = Ui_ComboBoxTutorial()
    ui.setupUi(ComboBoxTutorial)
    ComboBoxTutorial.show()
    sys.exit(app.exec_())
