# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_designs/textfields.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inputText = QtWidgets.QTextEdit(self.centralwidget)
        self.inputText.setGeometry(QtCore.QRect(20, 180, 261, 191))
        self.inputText.setObjectName("inputText")
        self.moveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.moveBtn.setGeometry(QtCore.QRect(330, 240, 89, 25))
        self.moveBtn.setObjectName("moveBtn")

        self.moveBtn.clicked.connect(self._copyText)

        self.outputText = QtWidgets.QTextBrowser(self.centralwidget)
        self.outputText.setGeometry(QtCore.QRect(480, 180, 261, 191))
        self.outputText.setObjectName("outputText")
        self.resetBtn = QtWidgets.QPushButton(self.centralwidget)
        self.resetBtn.setGeometry(QtCore.QRect(330, 300, 89, 25))
        self.resetBtn.setObjectName("resetBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.moveBtn.setText(_translate("MainWindow", "move"))
        self.resetBtn.setText(_translate("MainWindow", "reset"))

    def _copyText(self):
        # stores the contents of the text field into a variable
        text = self.inputText.toPlainText()
        print(text)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
